In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("./data/aggregate_mobility_05_04.csv")
data.head()

,date,state,Mobility,case_growth,confirmed_infections,death_rate,rt,days,phase_indi,days0,days1,days2,days3,days4,days5,days6
0,3/14/20,Rajasthan,-6.667297,-0.693147,3,0.000029,1.858568,1,-1,1,-1,-1,-1,-1,-1,-1
1,3/15/20,Rajasthan,-8.990548,-0.693147,1,0.000029,1.847345,2,-1,2,-1,-1,-1,-1,-1,-1
2,3/16/20,Rajasthan,-12.160472,0.000000,0,0.000030,1.837711,3,-1,3,-1,-1,-1,-1,-1,-1
3,3/17/20,Rajasthan,-16.243518,1.386294,0,0.000031,1.829966,4,-1,4,-1,-1,-1,-1,-1,-1
4,3/18/20,Rajasthan,-21.226916,-0.287682,3,0.000032,1.824285,5,-1,5,-1,-1,-1,-1,-1,-1

In [21]:
def get_label(df,col):
    '''
    Create a label to determine the change in mobility:
    if mobility[t+1] > mobility[t]: label_mob = 1
    else 0
    '''
    data_label = list(df[col])
    temp = data_label.copy()
    for i in range(len(data_label)-1):
        temp[i] = data_label[i+1] - data_label[i]
    temp[-1] = temp[-2]
    df['label_'+col] = temp
    df['label_'+col] = np.where(df['label_'+col]<0,1,0)
    return df

In [22]:
data_class_mobility = get_label(data,'Mobility')
data_class_mobility.head()

,date,state,Mobility,case_growth,confirmed_infections,death_rate,rt,days,phase_indi,days0,days1,days2,days3,days4,days5,days6,label,labelMobility,label_Mobility
0,3/14/20,Rajasthan,-6.667297,-0.693147,3,0.000029,1.858568,1,-1,1,-1,-1,-1,-1,-1,-1,1,0,1
1,3/15/20,Rajasthan,-8.990548,-0.693147,1,0.000029,1.847345,2,-1,2,-1,-1,-1,-1,-1,-1,1,0,1
2,3/16/20,Rajasthan,-12.160472,0.000000,0,0.000030,1.837711,3,-1,3,-1,-1,-1,-1,-1,-1,0,0,1
3,3/17/20,Rajasthan,-16.243518,1.386294,0,0.000031,1.829966,4,-1,4,-1,-1,-1,-1,-1,-1,0,0,1
4,3/18/20,Rajasthan,-21.226916,-0.287682,3,0.000032,1.824285,5,-1,5,-1,-1,-1,-1,-1,-1,1,0,1

In [23]:
data_class_case = get_label(data,'confirmed_infections')
data_class_case.head()

,date,state,Mobility,case_growth,confirmed_infections,death_rate,rt,days,phase_indi,days0,days1,days2,days3,days4,days5,days6,label,labelMobility,label_Mobility,label_confirmed_infections
0,3/14/20,Rajasthan,-6.667297,-0.693147,3,0.000029,1.858568,1,-1,1,-1,-1,-1,-1,-1,-1,1,0,1,1
1,3/15/20,Rajasthan,-8.990548,-0.693147,1,0.000029,1.847345,2,-1,2,-1,-1,-1,-1,-1,-1,1,0,1,1
2,3/16/20,Rajasthan,-12.160472,0.000000,0,0.000030,1.837711,3,-1,3,-1,-1,-1,-1,-1,-1,0,0,1,0
3,3/17/20,Rajasthan,-16.243518,1.386294,0,0.000031,1.829966,4,-1,4,-1,-1,-1,-1,-1,-1,0,0,1,0
4,3/18/20,Rajasthan,-21.226916,-0.287682,3,0.000032,1.824285,5,-1,5,-1,-1,-1,-1,-1,-1,1,0,1,1